name: Workflow k6 local
on: [push]
jobs:
  build:
    name: Run k6 local
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 local
        uses: grafana/k6-action@v0.2.0
        with:
          filename: script.js