name: Workflow k6 cloud
on: [push]
jobs:
  build:
    name: Run k6 cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 cloud
        uses: grafana/k6-action@v0.2.0
        with:
          filename: script-cloud.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}